### PR TITLE
Reorganized source code and files to properly build the py package, a…

### PR DESCRIPTION
**Pull request by jinkang23**
@ rhijjawi - Thanks for uploading the rest of the source code. 

I noticed the latest version `1.7.1` still did not fix the error `ModuleNotFoundError` so I took a stab at making some opinionated changes to reorganize the repository which seems to have fixed it. I can install the module locally and it imports without any errors now. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rhijjawi** [comment]
Thanks, I'm really sorry about this. It's my first python library so I was a bit lost. Excellent work @jinkang23

**Comment by rhijjawi** [comment]
How are you building the library, it's not working for me.

**Comment by jinkang23** [comment]
@rhijjawi  - once you have cloned GitHub repo locally, you can run this command to build/install the module locally:

`pip install -e ~/folder1/NextDNS-API`

or you can change dir to the cloned repo first..
`cd ~/folder1/NextDNS-API`
`pip install -e .`

**Comment by jinkang23** [comment]
@rhijjawi  - also, just confirmed the published version 1.7.2 is working now. Thanks for accepting this PR and publishing it :)

**Pull request merged**
